// Test scripts used to observe JSON formatting
console.log("\n\n```json\n{\n  \"build\": {\n    \"CPU\": {\n      \"model\": \"Intel Core i9-13900K\",\n      \"cores\": 24,\n      \"threads\": 32,\n      \"base_clock\": \"3.0 GHz\",\n      \"boost_clock\": \"5.8 GHz\",\n      \"cooler\": \"No\"\n    },\n    \"Storage_Device\": {\n      \"type\": \"NVMe SSD\",\n      \"model\": \"Samsung 970 EVO Plus\",\n      \"capacity\": \"2 TB\",\n      \"read_speed\": \"3500 MB/s\",\n      \"write_speed\": \"3300 MB/s\"\n    },\n    \"GPU\": {\n      \"model\": \"NVIDIA GeForce RTX 4080\",\n      \"memory\": \"16 GB GDDR6X\",\n      \"ray_tracing\": true\n    },\n    \"Motherboard\": {\n      \"model\": \"ASUS ROG Strix Z790-E Gaming WiFi\",\n      \"socket\": \"LGA 1700\",\n      \"features\": \"WiFi 6E, PCIe 5.0, USB 3.2 Gen 2x2\"\n    },\n    \"Computer_case\": {\n      \"model\": \"NZXT H510 Elite\",\n      \"form_factor\": \"Mid Tower\",\n      \"features\": \"Tempered glass, RGB lighting\"\n    },\n    \"Cooling\": {\n      \"model\": \"Corsair iCUE H150i Elite Capellix\",\n      \"type\": \"Liquid AIO Cooler\",\n      \"size\": \"360mm\"\n    }\n  }\n}\n```\n\n");
console.log("```json\n{\n  \"build\": {\n    \"CPU\": {\n      \"model\": \"AMD Ryzen 5 5600X\",\n      \"cores\": 6,\n      \"threads\": 12,\n      \"base_clock\": \"3.7 GHz\",\n      \"boost_clock\": \"4.6 GHz\",\n      \"TDP\": \"65W\"\n    },\n    \"GPU\": {\n      \"model\": \"NVIDIA GeForce RTX 3060\",\n      \"VRAM\": \"12GB\",\n      \"architecture\": \"Ampere\",\n      \"directx_support\": \"DirectX 12\"\n    },\n    \"Motherboard\": {\n      \"model\": \"MSI B550-A PRO\",\n      \"form_factor\": \"ATX\",\n      \"socket\": \"AM4\",\n      \"features\": [\n        \"PCIe 4.0 support\",\n        \"USB 3.2 Gen 1\",\n        \"DDR4 memory support up to 4400 MHz\"\n      ]\n    },\n    \"Storage_Device\": {\n      \"type\": \"SSD\",\n      \"model\": \"Crucial P3 500GB\",\n      \"interface\": \"NVMe PCIe Gen3\",\n      \"read_speed\": \"3500 MB/s\",\n      \"write_speed\": \"3000 MB/s\"\n    },\n    \"Computer_case\": {\n      \"model\": \"NZXT H510\",\n      \"form_factor\": \"Mid Tower\",\n      \"features\": [\n        \"Tempered glass side panel\",\n        \"Cable management system\",\n        \"Airflow optimization\"\n      ]\n    },\n    \"Cooling\": {\n      \"type\": \"Air Cooler\",\n      \"model\": \"Cooler Master Hyper 212 EVO\",\n      \"fan_size\": \"120mm\",\n      \"TDP_handling\": \"up to 150W\"\n    }\n  }\n}\n```");
console.log("```json\n{\n  \"PC_Build\": {\n    \"CPU\": {\n      \"model\": \"Ryzen 5 5600X\",\n      \"brand\": \"AMD\",\n      \"size\": \"6 cores, 12 threads\"\n    },\n    \"Storage_Device\": {\n      \"model\": \"Samsung 970 EVO Plus\",\n      \"brand\": \"Samsung\",\n      \"size\": \"1TB NVMe SSD\"\n    },\n    \"GPU\": {\n      \"model\": \"GeForce GTX 1660 Super\",\n      \"brand\": \"NVIDIA\",\n      \"size\": \"6GB GDDR6\"\n    },\n    \"Motherboard\": {\n      \"model\": \"MSI B550-A PRO\",\n      \"brand\": \"MSI\",\n      \"size\": \"ATX\"\n    },\n    \"Computer_Case\": {\n      \"model\": \"NZXT H510\",\n      \"brand\": \"NZXT\",\n      \"size\": \"Compact ATX Mid Tower\"\n    },\n    \"Cooling\": {\n      \"model\": \"Cooler Master Hyper 212 Black Edition\",\n      \"brand\": \"Cooler Master\",\n      \"size\": \"120mm\"\n    }\n  }\n}\n```");
console.log("json\n{\n  \"CPU\": {\n    \"model\": \"Ryzen 5 5600X\",\n    \"brand\": \"AMD\",\n    \"core_count\": 6,\n    \"thread_count\": 12,\n    \"base_clock\": \"3.7 GHz\",\n    \"boost_clock\": \"4.6 GHz\",\n    \"TDP\": \"65W\"\n  },\n  \"Storage_Device\": {\n    \"model\": \"Samsung 970 EVO Plus\",\n    \"brand\": \"Samsung\",\n    \"type\": \"SSD\",\n    \"capacity\": \"1TB\",\n    \"form_factor\": \"M.2 NVMe\",\n    \"read_speed\": \"3500 MB/s\",\n    \"write_speed\": \"3300 MB/s\"\n  },\n  \"GPU\": {\n    \"model\": \"GeForce GTX 1660 Super\",\n    \"brand\": \"NVIDIA\",\n    \"memory\": \"6GB GDDR6\",\n    \"memory_interface\": \"192-bit\",\n    \"boost_clock\": \"1785 MHz\"\n  },\n  \"Motherboard\": {\n    \"model\": \"B450 Tomahawk MAX\",\n    \"brand\": \"MSI\",\n    \"form_factor\": \"ATX\",\n    \"socket\": \"AM4\",\n    \"RAM_slots\": 4,\n    \"max_RAM_capacity\": \"64GB\",\n    \"PCIe_slots\": 3\n  },\n  \"Computer_case\": {\n    \"model\": \"NZXT H510\",\n    \"brand\": \"NZXT\",\n    \"form_factor\": \"ATX Mid Tower\",\n    \"dimensions\": {\n      \"height\": \"428mm\",\n      \"width\": \"210mm\",\n      \"depth\": \"460mm\"\n    },\n    \"features\": [\"Tempered Glass Side Panel\", \"Cable Management\", \"Fans Included\"]\n  },\n  \"Cooling\": {\n    \"model\": \"Cooler Master Hyper 212 RGB\",\n    \"brand\": \"Cooler Master\",\n    \"type\": \"Air Cooler\",\n    \"dimensions\": {\n      \"height\": \"158mm\",\n      \"width\": \"120mm\",\n      \"depth\": \"80mm\"\n    },\n    \"fan_speed\": \"2000 RPM\",\n    \"noise_level\": \"26 dBA\"\n  }\n}\n");
console.log("json\n{\n  \"CPU\": {\n    \"model\": \"Ryzen 5 5600X\",\n    \"brand\": \"AMD\"\n  },\n  \"Storage_Device\": {\n    \"model\": \"Crucial P3 500GB NVMe SSD\",\n    \"brand\": \"Crucial\"\n  },\n  \"GPU\": {\n    \"model\": \"GeForce RTX 3060\",\n    \"brand\": \"NVIDIA\"\n  },\n  \"Motherboard\": {\n    \"model\": \"B550M Pro-VDH WiFi\",\n    \"brand\": \"MSI\"\n  },\n  \"Computer_case\": {\n    \"model\": \"NZXT H510\",\n    \"brand\": \"NZXT\"\n  },\n  \"Cooling\": {\n    \"model\": \"Cooler Master Hyper 212 EVO\",\n    \"brand\": \"Cooler Master\"\n  }\n}\n");

// pc-part-dataset/data/json/cpu.json
// pc-part-dataset/data/json/memory.json
// NO GPU IN pc-part-dataset
// pc-part-dataset/data/json/motherboard.json
// pc-part-dataset/data/json/case.json
// pc-part-dataset/data/json/cpu-cooler.json